FROM containers.intersystems.com/intersystems/webgateway:2022.1.0.209.0

# apache: enable ssl
RUN a2enmod ssl
WORKDIR /etc/apache2/sites-enabled
RUN ln -s ../sites-available/default-ssl.conf default-ssl.conf

# ssl certificate
ENV ISC_WEB_HOST=webgateway
WORKDIR /etc/ssl

RUN openssl req -x509 -out ssl-cert.pem -keyout ssl-cert.key -newkey rsa:2048 -nodes -sha256 -days 365 -subj "/CN=${ISC_WEB_HOST}" -extensions EXT -config <(printf "[dn]\nCN=${ISC_WEB_HOST}\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:${ISC_WEB_HOST}\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
RUN cp ssl-cert.pem /etc/ssl/certs/ssl-cert-snakeoil.pem
RUN cp ssl-cert.key /etc/ssl/private/ssl-cert-snakeoil.key

# apache: CSP module config
ENV ISC_CSP_CONF_FILE=/etc/apache2/mods-available/CSP.conf
# webgateway config
ENV ISC_CSP_INI_FILE=/opt/webgateway/bin/CSP.ini

# run apache2
WORKDIR /
CMD ["apache2ctl -DFOREGROUND &"]