FROM docker.iscinternal.com/grongier/ucr:latest

COPY iris.script /tmp/iris.script
COPY src /tmp/scr

COPY key/iris.key /usr/healthshare/mgr/iris.key

# run iris and initial 
RUN iris start $ISC_PACKAGE_INSTANCENAME \
	&& iris session $ISC_PACKAGE_INSTANCENAME < /tmp/iris.script \
	&& iris stop IRIS quietly